import java.util.ArrayList;

// * PARTICPIANTS DO NOT EDIT THIS FILE - EDITING WILL RESULT IN DISQUALIFICATION OF ANSWER
public class ColonyBackend {
    public static void main(String[] args) throws Exception {
        int size = (int) (Math.random() * 16);

        ArrayList<Integer> hashList = new ArrayList<Integer>();

        if  (size == 0){
            size = 4;
        }

        Tile[] t = new Tile[size * size];
        int j = 0;
        int colonyCount = 0;

        for (int x = 0; x < size; x++){
            for (int y = 0; y < size; y++){
                boolean isColony = false;

                if (Math.random() > 0.9) {
                    isColony = true;
                    colonyCount++;    
                }

                t[j] = new Tile(Math.random() > 0.5 ? (int) (Math.random() * 8) : 0, isColony, x, y);
                hashList.add(t[j].hashCode());
                j++;
            }
        }

        if (colonyCount == 0) {
            int index = (int) (Math.random() * t.length);
            hashList.remove( (Object)t[index].hashCode());

            t[index] = new Tile(Math.random() > 0.5 ? (int) (Math.random() * 8) : 0, true, (int) (Math.random() * (int) Math.sqrt(t.length)), (int) (Math.random() * (int) Math.sqrt(t.length)));
            hashList.add(t[index].hashCode());
        }

        for (int s = 0; s < 10000; s++ ){
            for (int i = 0; i < 80; i++){
                t = Answer.simulationTick(t);
                j = 0;
                int a = -1;

                //  *Check for tile integrity
                for (Tile tile : t) {
                    if (!hashList.contains(tile.hashCode())){
                        throw new Exception("Adding new tiles in the solution is NOT allowed, make sure you are modifying the existing tiles");
                    }
                }
    
                for (Tile c : t){
                    if (c.isColony() && c.getResources() < 3){
                        throw new Exception("Completed " + i + " ticks and " + s + " successful simulations before a Colony went below 3 resources! Check your solution and run again");
                    }else if (c.isColony()){
                        if (a == -1) {
                            a = c.getResources();
                        }else{
                            if (Math.abs(c.getResources() - a) > 2){
                                throw new Exception("Completed " + i + " ticks before Colonies were unabalanced, make sure all colonies are within 2 resources of each other! Check your solution and run again");
                            }
                        }
                    }
                }
    
                for (int x = 0; x < size; x++){
                    for (int y = 0; y < size; y++){
                        boolean isColony = t[j].isColony();
        
                        hashList.remove( (Object)t[j].hashCode());
                        t[j] = new Tile(Math.random() > 0.5 && !isColony ? t[j].getResources() + (int) (Math.random() * 4) : isColony ? t[j].getResources() - (int) (Math.random() * t[j].getResources() - 1) : t[j].getResources(), isColony, t[j].getXPosition(), t[j].getYPosition());
                        hashList.add(t[j].hashCode());
    
                        j++;
                    }
                }
            }
        }
        

       System.out.println("Simulation Succeeded!");


    }
}