// * PARTICPIANTS DO NOT EDIT THIS FILE - EDITING WILL RESULT IN DISQUALIFICATION OF ANSWER
public class Tile {
    private int resources;
    private boolean hasColony;

    private int xPosition;
    private int yPosition;

    public Tile(int resources, boolean hasColony, int xPosition, int yPosition) {
        this.resources = resources;
        this.hasColony = hasColony;
        this.xPosition = xPosition;
        this.yPosition = yPosition;
    }

    public int getXPosition(){
        return xPosition;
    }

    public int getYPosition(){
        return yPosition;
    }

    public int getResources(){
        return resources;
    }

    public boolean isColony(){
        return hasColony;
    }

    private void setResources(int resources){
        this.resources = resources;
    }

    private double distFrom(Tile t){
        return Math.sqrt(Math.max(t.getXPosition(), xPosition) - Math.min(t.getXPosition(), xPosition) +  Math.max(t.getYPosition(), yPosition) - Math.min(t.getYPosition(), yPosition));
    }

    public void moveResourcesToOtherTile(Tile t, int amount){
        if (getResources() < amount) return;

        int deliveredResources = amount;

        if (distFrom(t) > 4){
            deliveredResources = amount / 2;
        }

        t.setResources(t.getResources() + deliveredResources);
        setResources(getResources() - amount);
    }
}