// * PARTICPIANTS DO NOT EDIT THIS FILE - EDITING WILL RESULT IN DISQUALIFICATION OF ANSWER
public class Tile {
    private int resources;
    private boolean hasColony;

    public Tile(int resources, boolean hasColony) {
        this.resources = resources;
        this.hasColony = hasColony;
    }

    public int getResources(){
        return resources;
    }

    public boolean isColony(){
        return hasColony;
    }

    private void setResources(int resources){
        this.resources = resources;
    }

    public void moveResourcesToOtherTile(Tile t, int amount){
        if (getResources() < amount) return;

        t.setResources(t.getResources() + amount);
        setResources(getResources() - amount);
    }
}